#INCLUDE<FCNTL.H>
#INCLUDE<UNISTD.H>
#INCLUDE<STDIO.H>

INT MAIN(INT ARGC, CHAR **ARGV){
	INT FD, NREAD, CNT, NUMCHAR = 0;
	CHAR BUFFER[1024];

	IF(ARGC < 2) RETURN 0;

	IF((FD = OPEN(ARGV[1], O_RDWR)) == -1){
		PRINTF("FILE OPEN ERROR\N");
		RETURN 0;
	}

	WHILE((NREAD = READ(FD, BUFFER, 1024)) > 0 ){
		FOR(CNT = 0; CNT < NREAD; CNT++){
			IF(BUFFER[CNT] >= 'A' && BUFFER[CNT] <= 'Z')
				BUFFER[CNT] -= 32;
		}
		LSEEK(FD, (OFF_T)-NREAD, SEEK_CUR);
		WRITE(FD, BUFFER, NREAD);
	}

	CLOSE(FD);
}
